-- 🔐 ACTUALIZAR CONTRASEÑA DE CAMILO - VERSIÓN SIMPLE
-- Ejecutar este script en Supabase SQL Editor

-- 1. Verificar estructura de la tabla
SELECT column_name, data_type FROM information_schema.columns WHERE table_name = 'usuarios' ORDER BY ordinal_position;

-- 2. Actualizar contraseña (usando columna 'password')
UPDATE usuarios 
SET password = '$2b$12$mJodKxTVgvzbTl1HqpHi1.lP8juay3aJ8o7l3FBRHNV7wdV18.dBu'
WHERE email LIKE '%camilo%';

-- 3. Verificar que se actualizó correctamente
SELECT 
    email,
    LEFT(password, 20) || '...' as password_actualizado,
    '✅ Contraseña actualizada' as estado
FROM usuarios 
WHERE email LIKE '%camilo%';

-- 4. Crear tabla mensajes (si no existe)
CREATE TABLE IF NOT EXISTS mensajes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    remitente_id BIGINT REFERENCES usuarios(id) ON DELETE SET NULL,
    destinatario_id BIGINT REFERENCES usuarios(id) ON DELETE SET NULL,
    asunto TEXT NOT NULL,
    contenido TEXT NOT NULL,
    categoria VARCHAR(50) DEFAULT 'general',
    prioridad VARCHAR(20) DEFAULT 'media',
    leido BOOLEAN DEFAULT FALSE,
    fecha_envio TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    creado_en TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 5. Verificar tabla mensajes
SELECT COUNT(*) as total_mensajes FROM mensajes;

-- Mensaje de confirmación
SELECT '✅ ¡CONTRASEÑA ACTUALIZADA CORRECTAMENTE!' as resultado;