-- 📨 CREAR TABLA MENSAJES
-- Esta tabla es necesaria para el sistema de notificaciones

-- Crear tabla mensajes
CREATE TABLE IF NOT EXISTS mensajes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    remitente_id BIGINT REFERENCES usuarios(id) ON DELETE SET NULL,
    destinatario_id BIGINT REFERENCES usuarios(id) ON DELETE SET NULL,
    asunto TEXT NOT NULL,
    contenido TEXT NOT NULL,
    categoria VARCHAR(50) DEFAULT 'general',
    prioridad VARCHAR(20) DEFAULT 'media',
    leido BOOLEAN DEFAULT FALSE,
    fecha_envio TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    fecha_lectura TIMESTAMP WITH TIME ZONE,
    creado_en TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    actualizado_en TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Crear índices para mejor rendimiento
CREATE INDEX IF NOT EXISTS idx_mensajes_destinatario ON mensajes(destinatario_id);
CREATE INDEX IF NOT EXISTS idx_mensajes_remitente ON mensajes(remitente_id);
CREATE INDEX IF NOT EXISTS idx_mensajes_categoria ON mensajes(categoria);
CREATE INDEX IF NOT EXISTS idx_mensajes_leido ON mensajes(leido);
CREATE INDEX IF NOT EXISTS idx_mensajes_fecha_envio ON mensajes(fecha_envio);

-- Insertar mensajes de ejemplo para el sistema
INSERT INTO mensajes (remitente_id, destinatario_id, asunto, contenido, categoria, prioridad) VALUES
(
    (SELECT id FROM usuarios WHERE email LIKE '%camilo%' LIMIT 1),
    (SELECT id FROM usuarios WHERE email LIKE '%camilo%' LIMIT 1),
    'Bienvenido al Sistema',
    'Tu cuenta ha sido configurada correctamente. Ahora puedes acceder a todas las funcionalidades del sistema.',
    'bienvenida',
    'baja'
),
(
    (SELECT id FROM usuarios WHERE email LIKE '%camilo%' LIMIT 1),
    (SELECT id FROM usuarios WHERE email LIKE '%camilo%' LIMIT 1),
    'Campañas Pendientes',
    'Tienes 3 campañas esperando revisión. Por favor revisa el módulo de campañas.',
    'campanas',
    'media'
),
(
    (SELECT id FROM usuarios WHERE email LIKE '%camilo%' LIMIT 1),
    (SELECT id FROM usuarios WHERE email LIKE '%camilo%' LIMIT 1),
    'Nueva Orden de Compra',
    'Se ha creado una nueva orden de compra que requiere tu aprobación.',
    'ordenes',
    'alta'
);

-- Verificar que la tabla se creó correctamente
SELECT 
    'mensajes' as tabla,
    column_name,
    data_type,
    is_nullable
FROM information_schema.columns 
WHERE table_name = 'mensajes' 
    AND table_schema = 'public'
ORDER BY ordinal_position;

-- Mostrar mensajes insertados
SELECT 
    id,
    asunto,
    categoria,
    prioridad,
    leido,
    fecha_envio
FROM mensajes 
ORDER BY fecha_envio DESC;

-- Confirmación
DO $$
BEGIN
    RAISE NOTICE '✅ Tabla mensajes creada correctamente';
    RAISE NOTICE '📨 Se insertaron 3 mensajes de ejemplo';
    RAISE NOTICE '🔍 El sistema de notificaciones ahora funcionará correctamente';
END $$;